name: Github Actions CI - Build

on:
  push:
   branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
    
    permissions:
      contents: read
      packages: write 
    
    env:
      REPOSITORY_NAME: "ghcr.io/williampasset/tp05-devops"
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ env.REPOSITORY_NAME }}:${{ github.sha }}
          ${{ env.REPOSITORY_NAME }}:latest
