name: Deploy to Coolify

on:
  push:
    branches:
      - develop  
      - main

jobs:
  deploy:
    name: Trigger Coolify Deployment
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Triggering Coolify deployment
        env:
          COOLIFY_WEBHOOK: ${{ secrets.COOLIFY_WEBHOOK }}
          TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: |
          echo "Triggering Coolify deployment..."
          curl --location --request POST "$COOLIFY_WEBHOOK" \
            --header "Authorization: Bearer $TOKEN" \
            --header "Content-Type: application/json" \
            --data '{}'